version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: coworking-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: coworking-platform
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - coworking-network

  # Redis for caching and sessions
  redis:
    image: redis:7.2-alpine
    container_name: coworking-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - coworking-network

  # Next.js Application (Unified Platform)
  app:
    build:
      context: .
      target: development
    container_name: coworking-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://admin:password@mongodb:27017/coworking-platform?authSource=admin
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/coworking-platform?authSource=admin
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=development-secret-key-12345678901234567890
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - mongodb
      - redis
    networks:
      - coworking-network
    command: npm run dev

volumes:
  mongodb_data:
  redis_data:

networks:
  coworking-network:
    driver: bridge
