# Configuration Netlify pour Next.js
[build]
  publish = ".next"
  command = "npm run build"

# Variables d'environnement par défaut
[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# Redirections pour Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Gestion des API routes Next.js sur Netlify
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Cache statique
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"