packages:
  # Applications
  - 'apps/*'
  
  # Shared packages
  - 'packages/*'
  
  # Development tools
  - 'tools/*'

# pnpm configuration
catalog:
  # React ecosystem
  react: ^18.2.0
  react-dom: ^18.2.0
  next: ^14.1.0
  
  # TypeScript
  typescript: ^5.1.6
  '@types/react': ^18.2.0
  '@types/react-dom': ^18.2.0
  '@types/node': ^20.0.0
  
  # Styling - Tailwind CSS v3 (stable)
  tailwindcss: ^3.4.0
  autoprefixer: ^10.4.0
  postcss: ^8.4.0
  
  # Database
  mongoose: ^8.0.0
  '@types/mongoose': ^5.11.97
  
  # Authentication
  next-auth: ^4.24.0
  
  # Payment
  stripe: ^14.0.0
  '@stripe/stripe-js': ^2.0.0
  
  # UI Components
  '@radix-ui/react-slot': ^1.0.2
  '@radix-ui/react-dialog': ^1.0.5
  '@radix-ui/react-dropdown-menu': ^2.0.6
  'class-variance-authority': ^0.7.0
  'clsx': ^2.0.0
  'tailwind-merge': ^2.0.0
  'lucide-react': ^0.294.0
  
  # Validation
  zod: ^3.22.0
  
  # Environment management
  '@t3-oss/env-nextjs': ^0.7.0
  '@t3-oss/env-core': ^0.7.0
  
  # Development tools
  eslint: ^8.48.0
  prettier: ^3.0.2
  turbo: ^2.5.5