name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8.15.0'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Auto-merge minor and patch updates
        if: success()
        run: |
          # Get the dependency update type
          PR_TITLE="${{ github.event.pull_request.title }}"
          
          if [[ "$PR_TITLE" == *"Bump"* ]] && [[ "$PR_TITLE" != *"major"* ]]; then
            echo "Auto-merging dependency update"
            gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
          else
            echo "Major update detected, manual review required"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}